// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cadastrarConta": {
            "post": {
                "description": "Cadastrar uma nova conta no sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cadastrar"
                ],
                "summary": "Cadastrar uma nova conta no sistema.",
                "parameters": [
                    {
                        "description": "Objeto",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.cadastrarContaRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cadastrarDadosCompletos": {
            "post": {
                "description": "Cadastrar uma nova conta no sistema com seus dados completos como pessoa, endereço e contato.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cadastrar"
                ],
                "summary": "Cadastrar uma nova conta no sistema com seus dados completos como pessoa, endereço e contato.",
                "parameters": [
                    {
                        "description": "Objeto",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.cadastrarDadosCompletosRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/health": {
            "get": {
                "description": "Rota para verificar o servidor ON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Rota para verificar o servidor ON.",
                "responses": {}
            }
        }
    },
    "definitions": {
        "controllers.cadastrarContaRequest": {
            "type": "object",
            "properties": {
                "conta": {
                    "$ref": "#/definitions/repositories.CadastrarContaArgs"
                }
            }
        },
        "controllers.cadastrarDadosCompletosRequest": {
            "type": "object",
            "properties": {
                "conta": {
                    "$ref": "#/definitions/repositories.CadastrarContaArgs"
                },
                "pessoa": {
                    "$ref": "#/definitions/repositories.CadastrarPessoaArgs"
                }
            }
        },
        "repositories.CadastrarContaArgs": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "foto_perfil": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "repositories.CadastrarPessoaArgs": {
            "type": "object",
            "properties": {
                "data_nascimento": {
                    "type": "string"
                },
                "genero": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "sobrenome": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "USER FLOW CRUD",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
