definitions:
  controllers.cadastrarContaRequest:
    properties:
      conta:
        $ref: '#/definitions/repositories.CadastrarContaArgs'
    type: object
  controllers.cadastrarDadosCompletosRequest:
    properties:
      conta:
        $ref: '#/definitions/repositories.CadastrarContaArgs'
      pessoa:
        $ref: '#/definitions/repositories.CadastrarPessoaArgs'
    type: object
  repositories.CadastrarContaArgs:
    properties:
      ativo:
        type: boolean
      email:
        type: string
      foto_perfil:
        type: string
      senha:
        type: string
    type: object
  repositories.CadastrarPessoaArgs:
    properties:
      data_nascimento:
        type: string
      genero:
        type: string
      nome:
        type: string
      sobrenome:
        type: string
    type: object
info:
  contact: {}
  title: USER FLOW CRUD
  version: "1.0"
paths:
  /cadastrarConta:
    post:
      consumes:
      - application/json
      description: Cadastrar uma nova conta no sistema.
      parameters:
      - description: Objeto
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controllers.cadastrarContaRequest'
      produces:
      - application/json
      responses: {}
      summary: Cadastrar uma nova conta no sistema.
      tags:
      - Cadastrar
  /cadastrarDadosCompletos:
    post:
      consumes:
      - application/json
      description: Cadastrar uma nova conta no sistema com seus dados completos como
        pessoa, endereço e contato.
      parameters:
      - description: Objeto
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/controllers.cadastrarDadosCompletosRequest'
      produces:
      - application/json
      responses: {}
      summary: Cadastrar uma nova conta no sistema com seus dados completos como pessoa,
        endereço e contato.
      tags:
      - Cadastrar
  /health:
    get:
      consumes:
      - application/json
      description: Rota para verificar o servidor ON.
      produces:
      - application/json
      responses: {}
      summary: Rota para verificar o servidor ON.
      tags:
      - Health
swagger: "2.0"
